using System;
using Credfeto.Database.Source.Generation.Builders;
using FunFair.Test.Common;
using Microsoft.CodeAnalysis.Text;
using Xunit;

namespace Credfeto.Database.Source.Generation.Tests.Builders;

public sealed class CodeBuilderTests : TestBase
{
    [Fact]
    public void EmptyBuilderHasEmptyText()
    {
        CodeBuilder builder = new();
        SourceText text = builder.Text;
        Assert.NotNull(text);
        Assert.Equal(expected: string.Empty, actual: text.ToString());
    }

    [Fact]
    public void AppendLineAddsText()
    {
        CodeBuilder builder = new();
        builder.AppendLine("Hello World");
        string result = builder.Text.ToString();
        Assert.Contains("Hello World", result, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendBlankLineAddsNewline()
    {
        CodeBuilder builder = new();
        builder.AppendLine("First");
        builder.AppendBlankLine();
        builder.AppendLine("Second");
        string result = builder.Text.ToString();
        Assert.Contains("First", result, StringComparison.Ordinal);
        Assert.Contains("Second", result, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendLineWithWhiteSpaceAppendsBlankLine()
    {
        CodeBuilder builder = new();
        builder.AppendLine("   ");
        string result = builder.Text.ToString();
        // whitespace-only strings go through AppendBlankLine path
        Assert.True(result.Length > 0, userMessage: "Should have produced some content");
    }

    [Fact]
    public void AppendFileHeaderAddsHeaderContent()
    {
        CodeBuilder builder = new();
        builder.AppendFileHeader();
        string result = builder.Text.ToString();
        Assert.Contains("<auto-generated>", result, StringComparison.Ordinal);
    }

    [Fact]
    public void AppendGeneratedCodeAttributeAddsAttribute()
    {
        CodeBuilder builder = new();
        builder.AppendGeneratedCodeAttribute();
        string result = builder.Text.ToString();
        Assert.Contains("[GeneratedCode(", result, StringComparison.Ordinal);
    }

    [Fact]
    public void StartBlockAddsIndentation()
    {
        CodeBuilder builder = new();
        using (builder.StartBlock("namespace Test"))
        {
            builder.AppendLine("// inner");
        }

        string result = builder.Text.ToString();
        Assert.Contains("namespace Test", result, StringComparison.Ordinal);
        Assert.Contains("{", result, StringComparison.Ordinal);
        Assert.Contains("}", result, StringComparison.Ordinal);
        Assert.Contains("// inner", result, StringComparison.Ordinal);
    }

    [Fact]
    public void StartBlockWithCustomBracesUsesCustomBraces()
    {
        CodeBuilder builder = new();
        using (builder.StartBlock(text: "HEADER", start: "[", end: "]"))
        {
            builder.AppendLine("item");
        }

        string result = builder.Text.ToString();
        Assert.Contains("HEADER", result, StringComparison.Ordinal);
        Assert.Contains("[", result, StringComparison.Ordinal);
        Assert.Contains("]", result, StringComparison.Ordinal);
        Assert.Contains("item", result, StringComparison.Ordinal);
    }

    [Fact]
    public void NestedBlocksProduceIncreasingIndentation()
    {
        CodeBuilder builder = new();
        using (builder.StartBlock("outer"))
        {
            using (builder.StartBlock("inner"))
            {
                builder.AppendLine("deep");
            }
        }

        string result = builder.Text.ToString();
        Assert.True(result.Contains("inner", StringComparison.Ordinal), userMessage: "Should contain 'inner'");
        Assert.True(result.Contains("deep", StringComparison.Ordinal), userMessage: "Should contain 'deep'");
    }

    [Fact]
    public void AppendLineReturnsBuilder()
    {
        CodeBuilder builder = new();
        CodeBuilder returned = builder.AppendLine("test");
        Assert.Same(expected: builder, actual: returned);
    }

    [Fact]
    public void AppendBlankLineReturnsBuilder()
    {
        CodeBuilder builder = new();
        CodeBuilder returned = builder.AppendBlankLine();
        Assert.Same(expected: builder, actual: returned);
    }

    [Fact]
    public void AppendFileHeaderReturnsBuilder()
    {
        CodeBuilder builder = new();
        CodeBuilder returned = builder.AppendFileHeader();
        Assert.Same(expected: builder, actual: returned);
    }

    [Fact]
    public void AppendGeneratedCodeAttributeReturnsBuilder()
    {
        CodeBuilder builder = new();
        CodeBuilder returned = builder.AppendGeneratedCodeAttribute();
        Assert.Same(expected: builder, actual: returned);
    }

    [Fact]
    public void TextHasUtf8Encoding()
    {
        CodeBuilder builder = new();
        builder.AppendLine("test");
        SourceText text = builder.Text;
        Assert.NotNull(text.Encoding);
        Assert.Equal(expected: System.Text.Encoding.UTF8, actual: text.Encoding);
    }
}
